[build-system]
requires = ["setuptools>=61.0"]
build-backend= "setuptools.build_meta"
[project]
name = "pypinetworktest_ttataryn26"
version = "0.4"
authors = [ {name="Example author", email = "Author@example.com"}]
description = "test pypi network traffic"
readme = "README.md"
