[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "df-to-db"
authors = [
    {name = "Masum Billal", email = "billalmasum93@gmail.com"},
]
description = "An awesome package that can write pandas dataframe to different databases"
readme = "README.md"
requires-python = ">=3.6"
license = {file = "LICENSE"}

dependencies = [
    "pandas",
    "pymysql",
    "cryptography",
    "pymongo",
    "sqlalchemy <= 1.4.0",
    "requests",
    "mysqlclient",
    "sphinx",
    "sphinx-book-theme",
    "sphinx-rtd-theme",
    "psycopg2-binary",
    "sqlalchemy-utils",
    "dnspython",
    "pymssql",
    "google-cloud-bigquery",
    "pyarrow",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "pytest",
    "coverage",
    "tox",
    "black",
    "flake8",
]


[project.urls]
Homepage = "https://github.com/proafxin/df_to_db"


[tool.setuptools.packages.find]
exclude = ["tests*"] 
