[tool.poetry]
name = "shirasu"
version = "1.0.1"
description = "A simple bot framework to study the principles, based on OneBot v11."
authors = ["kifuan <kifuan@foxmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ujson = "^5.7.0"
websockets = "^10.4"
loguru = "^0.6.0"
pydantic = "^1.10.4"
pyyaml = "^6.0"


[tool.poetry.group.dev.dependencies]
mypy = "^0.991"
types-ujson = "^5.7.0.0"
pytest = "^7.2.1"
pytest-asyncio = "^0.20.3"
flake8 = "^6.0.0"
types-pyyaml = "^6.0.12.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
