[tool.poetry]

name = "dep-search"
version = "0.1.0"
description = "Search dep"
authors = ["everhide <i.tolkachnikov@gmail.com>"]

packages = [
    { include = "search" },
]

[tool.poetry.dependencies]
python = ">=3.9 <=3.11"
poetry = "1.1.15"
httpx = "^0.23.3"
dep-module-mongo = "^2.13.29"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

