[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aiocontroller"
version = "0.0.1"
authors = [{ name = "Evan Aranda" }]
description = "Adapter controller classes to aiohttp server routes."
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/EvanAranda/aiocontroller"