
[build-system]
requires = ["setuptools>=61.0", "nestifydict"]
build-backend = "setuptools.build_meta"

[project]
name = "reconfigurator"
version = "0.1.3"
authors = [
  { name="Jared J. Beard", email="jbeard6@mix.wvu.edu" },
]
description = "The purpose of this project is to provide an interface for nested dictionaries with unknown structures"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]

[tools.setuptools]
include-package-data = true
where = ["reconfigurator"]

[project.urls]
"Homepage" = "https://github.com/jaredjbeard/reconfigurator"
"Documentation" = "https://reconfigurator.readthedocs.io/en/latest/introduction.html"