[project]
name = "flatiron"
version = "0.14.1"
description = "A library of custom computer vision models."
readme = "README.md"
license = "MIT"
keywords = []
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Typing :: Typed",
]
requires-python = ">=3.8"
dependencies = [
    "click>=8.1.3",
    "humanfriendly",
    "lunchbox>=0.3.3",
    "numpy",
    "pandas",
    "pytz>=2022.7.1",
    "pyyaml>=6.0",
    "schematics>=2.1.1",
    "scikit-learn>=1.2.1",
    "tensorboard>=2.0.0",
    "tqdm>=4.64.1",
    "tensorflow>=2.0.0",
]
authors = [
    { name = "Alex Braun", email = "alexander.g.braun@gmail.com" },
]

[project.urls]
repository = "https://github.com/thenewflesh/flatiron"
documentation = "https://thenewflesh.github.io/flatiron"

[project.scripts]
flatiron = "flatiron.command:main"

[project.optional-dependencies]

[build-system]
requires = [
    "pdm-pep517>=1.0.0",
]
build-backend = "pdm.pep517.api"

[tool.coverage.report]
show_missing = true
omit = [
    "*/__init__.py",
    "*/*_test_base.py",
    "*/*_test.py",
    "*/*_tests.py",
    "*/cli.py",
    "*/command.py",
    "*/mock_*.py",
    "*/conftest.py",
]
