[tool.poetry]
name = "dockertk"
version = "1.0.21"
description = ""
authors = ["wayfaring-stranger <zw6p226m@duck.com>"]
packages = [
    { include = "dockertk" }
]


license = "mit"
readme = "README.md"
[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

